version: '2'

services:
  postgresql-master:
    image: 'bitnami/postgresql:latest'
    ports:
      - 5432:5432
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    environment:
#      - POSTGRESQL_REPLICATION_MODE=master
#      - POSTGRESQL_REPLICATION_USER=repl_user
#      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_DATABASE=my_database

volumes:
  postgresql_master_data:
